kind: pipeline
type: docker
name: default
steps:
- name: test
  image: alpine
  commands:
  - echo "It worked"
  
- name: slack-end
  image: plugins/slack
  settings:
    webhook:
      from_secret: SlackWebhook
