kind: pipeline
type: docker
name: deploy

steps:
- name: test
  image: node
  commands:
  - npm install
  - npm run test
  - npm run bundle

- name: deploy
  image: plugins/ssh
  settings: ...
  when:
    event:
    - promote
    target:
    - production
