kind: pipeline
name: default

steps:
- name: build
  image: alpine
  environment:
    USERNAME:
      from_secret: username

---
kind: secret
name: username
data: MAfl5fxBkAzxfcZfKGa+gz8/N++UJ8blfJr17BVnNc0sdo62h5tJBg42nw==
