Steps:
- name: test
  image: alpine
  commands:
  - echo "It worked"
  
- name: slack-end
  image: plugins/slack
  settings:
    webhook:
      from_secret: SlackWebhook
      template: >
      {{repo.name}}/{{build.branch}} - #{{build.number}} {{uppercasefirst build.status}} after {{since build.started}} (<{{build.link}}|Open>)
